const MXN = new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0});
const today = new Date().toISOString().slice(0,10);
const state = {
  page:'dashboard',
  products:[
    {id:'PRD-0001',name:'Mini compresor portátil 150 PSI',emoji:'🛞',source:'AliExpress',sourceUrl:'https://www.aliexpress.com/',cost:218,landed:247,stock:12,reserved:1,marketPrice:449,status:'En stock',category:'Automotriz',comparisons:[{source:'Mercado Libre',price:449,url:'https://www.mercadolibre.com.mx/',date:'—',mode:'Ejemplo'},{source:'Amazon',price:479,url:'https://www.amazon.com.mx/',date:'—',mode:'Ejemplo'},{source:'Soriana',price:499,url:'https://www.soriana.com/',date:'—',mode:'Ejemplo'}]},
    {id:'PRD-0002',name:'Lámpara LED recargable magnética',emoji:'💡',source:'Temu',sourceUrl:'https://www.temu.com/',cost:82,landed:116,stock:24,reserved:3,marketPrice:289,status:'En stock',category:'Hogar',comparisons:[{source:'Mercado Libre',price:299,url:'https://www.mercadolibre.com.mx/',date:'—',mode:'Ejemplo'},{source:'Amazon',price:279,url:'https://www.amazon.com.mx/',date:'—',mode:'Ejemplo'}]},
    {id:'PRD-0003',name:'Organizador plegable para cajuela',emoji:'🚙',source:'AliExpress',sourceUrl:'https://www.aliexpress.com/',cost:96,landed:139,stock:5,reserved:0,marketPrice:329,status:'Stock bajo',category:'Automotriz',comparisons:[{source:'Mercado Libre',price:349,url:'https://www.mercadolibre.com.mx/',date:'—',mode:'Ejemplo'}]},
    {id:'PRD-0004',name:'Selladora térmica mini USB',emoji:'📦',source:'Temu',sourceUrl:'https://www.temu.com/',cost:54,landed:79,stock:0,reserved:0,marketPrice:199,status:'En tránsito',category:'Hogar',comparisons:[]},
  ],
  ideas:[
    {id:'IDE-0012',name:'Aspiradora portátil USB-C',detail:'Costo estimado $178 · precio observado $399-$499',stage:'Votación',votes:{yes:3,maybe:1,no:0}},
    {id:'IDE-0013',name:'Impresora térmica etiquetas',detail:'AliExpress · pedido mínimo 5 piezas',stage:'Investigación',votes:{yes:1,maybe:2,no:0}},
    {id:'IDE-0014',name:'Luz ambiente RGB para auto',detail:'Temu · margen preliminar 46%',stage:'Nueva',votes:{yes:2,maybe:0,no:1}},
    {id:'IDE-0011',name:'Dispensador automático jabón',detail:'Aprobado para prueba de 10 piezas',stage:'Aprobada',votes:{yes:4,maybe:0,no:0}},
  ],
  sales:[
    {id:'VEN-0007',date:'2026-09-23',product:'Mini compresor portátil 150 PSI',seller:'Roberto',channel:'Facebook Marketplace',price:430,cost:247,shipping:55,platformFee:0,other:0,sellerPct:20},
    {id:'VEN-0006',date:'2026-09-22',product:'Lámpara LED recargable magnética',seller:'Carlos',channel:'Venta física',price:260,cost:116,shipping:0,platformFee:0,other:10,sellerPct:20},
    {id:'VEN-0005',date:'2026-09-20',product:'Organizador plegable para cajuela',seller:'Ana',channel:'Facebook Marketplace',price:310,cost:139,shipping:65,platformFee:0,other:0,sellerPct:15},
    {id:'VEN-0004',date:'2026-09-19',product:'Lámpara LED recargable magnética',seller:'Roberto',channel:'Instagram',price:280,cost:116,shipping:45,platformFee:0,other:0,sellerPct:20},
  ],
  members:[
    {name:'Roberto',role:'Administrador / Ventas'},{name:'Carlos',role:'Compras / Ventas'},{name:'Ana',role:'Inventario / Ventas'},{name:'Socio 4',role:'Socio / Ideas'}
  ],
  settings:{aiProvider:'OpenAI',aiModel:'',comparisonSources:['Amazon','Mercado Libre'],defaultSellerPct:20}
};

const navItems=[
  ['dashboard','⌂','Dashboard'],['products','▦','Productos'],['ideas','💡','Ideas y votación'],['purchases','🚢','Compras'],['sales','＄','Ventas'],['team','👥','Equipo y balances'],['settings','⚙','Configuración']
];
const $=s=>document.querySelector(s); const el=(tag,cls='')=>{const e=document.createElement(tag);e.className=cls;return e};

function renderNav(){
  $('#mainNav').innerHTML=navItems.map(([id,icon,label])=>`<button data-page="${id}" class="${state.page===id?'active':''}"><span class="nav-icon">${icon}</span>${label}</button>`).join('');
  $('#mainNav').querySelectorAll('button').forEach(b=>b.onclick=()=>go(b.dataset.page));
  const mobile=navItems.slice(0,5);
  $('#mobileNav').innerHTML=mobile.map(([id,icon,label])=>`<button data-page="${id}" class="${state.page===id?'active':''}"><span>${icon}</span>${label.split(' ')[0]}</button>`).join('');
  $('#mobileNav').querySelectorAll('button').forEach(b=>b.onclick=()=>go(b.dataset.page));
}
function go(page){state.page=page;$('#sidebar').classList.remove('open');render();}
function render(){renderNav();const meta={dashboard:['OPERACIÓN','Dashboard'],products:['CATÁLOGO','Productos e inventario'],ideas:['DECISIÓN','Ideas y votación'],purchases:['ABASTECIMIENTO','Compras e importación'],sales:['RESULTADOS','Ventas y utilidad real'],team:['EQUIPO','Balances por persona'],settings:['SISTEMA','Configuración']}[state.page];$('#eyebrow').textContent=meta[0];$('#pageTitle').textContent=meta[1];({dashboard:renderDashboard,products:renderProducts,ideas:renderIdeas,purchases:renderPurchases,sales:renderSales,team:renderTeam,settings:renderSettings}[state.page])();}

function profit(s){return s.price-s.cost-s.shipping-s.platformFee-s.other} function sellerCommission(s){return Math.max(0,profit(s))*s.sellerPct/100} function businessProfit(s){return profit(s)-sellerCommission(s)}
function metric(label,value,icon,foot,positive=false){return `<div class="metric-card"><div class="metric-top"><span>${label}</span><span class="metric-icon">${icon}</span></div><strong>${value}</strong><small class="${positive?'positive':''}">${foot}</small></div>`}
function renderDashboard(){
  const stockValue=state.products.reduce((a,p)=>a+p.landed*p.stock,0), sales=state.sales.reduce((a,s)=>a+s.price,0), net=state.sales.reduce((a,s)=>a+businessProfit(s),0), units=state.products.reduce((a,p)=>a+p.stock,0);
  $('#content').innerHTML=`
    <div class="grid metrics">${metric('Capital en inventario',MXN.format(stockValue),'📦','Costo puesto en México')}${metric('Ventas registradas',MXN.format(sales),'💳','Datos demo actuales',true)}${metric('Utilidad negocio',MXN.format(net),'↗','Después de gastos y comisión',true)}${metric('Unidades disponibles',units,'▦',`${state.products.filter(p=>p.stock<=5).length} productos con stock bajo`)}</div>
    <div class="section-head"><div><h2>Operación actual</h2><p>Productos con movimiento y señales importantes.</p></div><button class="ghost-btn" onclick="go('products')">Ver inventario</button></div>
    <div class="grid two-col"><div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Producto</th><th>Stock</th><th>Costo</th><th>Mercado</th><th>Margen potencial</th></tr></thead><tbody>${state.products.map(p=>`<tr><td><div class="product-cell"><div class="product-thumb">${p.emoji}</div><div><strong>${p.name}</strong><span>${p.id} · ${p.source}</span></div></div></td><td><span class="badge ${p.stock<=5?'amber':'green'}">${p.stock} uds</span></td><td>${MXN.format(p.landed)}</td><td>${MXN.format(p.marketPrice)}</td><td><strong>${Math.round((p.marketPrice-p.landed)/p.marketPrice*100)}%</strong></td></tr>`).join('')}</tbody></table></div></div>
    <div class="card"><div class="card-pad"><strong style="font-size:14px">Actividad del equipo</strong><p style="font-size:11px;color:var(--muted);margin:4px 0 0">Últimos movimientos registrados</p></div><div class="list">${state.sales.slice(0,4).map(s=>`<div class="list-item"><div class="list-main"><div class="list-icon">💰</div><div><strong>${s.seller} registró ${s.id}</strong><span>${s.product} · ${s.channel}</span></div></div><span class="money positive">+${MXN.format(businessProfit(s))}</span></div>`).join('')}</div></div></div>
    <div class="section-head"><div><h2>Ideas pendientes</h2><p>Lo que el equipo está evaluando para invertir.</p></div><button class="ghost-btn" onclick="go('ideas')">Ir a votaciones</button></div>
    <div class="card"><div class="list">${state.ideas.filter(i=>i.stage!=='Aprobada').slice(0,4).map(i=>`<div class="list-item"><div class="list-main"><div class="list-icon">💡</div><div><strong>${i.name}</strong><span>${i.detail}</span></div></div><div><span class="badge blue">👍 ${i.votes.yes}</span> <span class="badge">🤔 ${i.votes.maybe}</span></div></div>`).join('')}</div></div>`;
}
function renderProducts(){
  $('#content').innerHTML=`<div class="toolbar"><input class="search" id="productSearch" placeholder="Buscar producto, SKU o proveedor…"><div class="filters"><select class="select" id="stockFilter"><option>Todos</option><option>En stock</option><option>Stock bajo</option><option>En tránsito</option></select><button class="primary-btn" id="addProductBtn">＋ Producto</button></div></div><div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Producto</th><th>Estado</th><th>Stock</th><th>Costo real</th><th>Referencia</th><th>Comparaciones</th><th></th></tr></thead><tbody id="productRows"></tbody></table></div></div>`;
  const draw=()=>{const q=$('#productSearch').value.toLowerCase(),f=$('#stockFilter').value;const rows=state.products.filter(p=>(p.name+p.id+p.source).toLowerCase().includes(q)&&(f==='Todos'||p.status===f));$('#productRows').innerHTML=rows.map(p=>`<tr><td><div class="product-cell"><div class="product-thumb">${p.emoji}</div><div><strong>${p.name}</strong><span>${p.id} · ${p.category}</span></div></div></td><td><span class="badge ${p.status==='En stock'?'green':p.status==='Stock bajo'?'amber':'blue'}">${p.status}</span></td><td><strong>${p.stock-p.reserved}</strong><span style="color:var(--muted);font-size:10px"> / ${p.stock}</span></td><td>${MXN.format(p.landed)}</td><td>${MXN.format(p.marketPrice)}</td><td>${p.comparisons.length} fuentes</td><td><button class="link-btn" data-detail="${p.id}">Abrir →</button></td></tr>`).join('')||`<tr><td colspan="7"><div class="empty">Sin resultados</div></td></tr>`;document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>openProduct(b.dataset.detail));};draw();$('#productSearch').oninput=draw;$('#stockFilter').onchange=draw;$('#addProductBtn').onclick=openAddProduct;
}
function openProduct(id){const p=state.products.find(x=>x.id===id);const avg=p.comparisons.length?Math.round(p.comparisons.reduce((a,c)=>a+c.price,0)/p.comparisons.length):0;showModal(`Producto ${p.id}`,p.name,`<div class="compare-grid"><div class="compare-box"><span>Costo puesto en México</span><strong>${MXN.format(p.landed)}</strong></div><div class="compare-box"><span>Stock disponible</span><strong>${p.stock-p.reserved} unidades</strong></div><div class="compare-box"><span>Promedio referencias</span><strong>${avg?MXN.format(avg):'Sin datos'}</strong></div></div><div class="separator"></div><div class="tabs"><button class="tab active">Comparativas</button><button class="tab">Inventario</button><button class="tab">Proveedor</button></div><div class="section-head" style="margin-top:0"><div><h2>Referencias de mercado</h2><p>Automáticas o capturadas manualmente.</p></div><div><button class="secondary-btn" onclick="fakeAISearch('${p.id}')">🤖 Buscar similares</button> <button class="primary-btn" onclick="addComparison('${p.id}')">＋ Manual</button></div></div><div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Fuente</th><th>Precio</th><th>Origen</th><th>Fecha</th><th></th></tr></thead><tbody>${p.comparisons.map((c,i)=>`<tr><td><strong>${c.source}</strong></td><td>${MXN.format(c.price)}</td><td><span class="badge ${c.mode==='IA'?'blue':''}">${c.mode}</span></td><td>${c.date}</td><td><a class="link-btn" href="${c.url}" target="_blank" rel="noopener">Abrir ↗</a></td></tr>`).join('')||`<tr><td colspan="5"><div class="empty">Aún no hay referencias. Puedes buscarlas con IA o agregarlas manualmente.</div></td></tr>`}</tbody></table></div></div><div class="separator"></div><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="primary-btn" onclick="prepareMarketplace('${p.id}')">📢 Preparar Marketplace</button><button class="secondary-btn" onclick="openSale('${p.id}')">💰 Registrar venta</button></div>`);
}
function openAddProduct(){showModal('Nuevo producto','Registrar producto o mercancía',`<div class="form-grid"><div class="field full"><label>NOMBRE</label><input id="pName" placeholder="Ej. Mini aspiradora portátil"></div><div class="field"><label>PROVEEDOR</label><select id="pSource"><option>AliExpress</option><option>Temu</option><option>Otro</option></select></div><div class="field"><label>CATEGORÍA</label><input id="pCat" placeholder="Hogar, Auto, Bebé…"></div><div class="field"><label>COSTO UNITARIO</label><input id="pCost" type="number" min="0"></div><div class="field"><label>COSTO REAL / LANDED</label><input id="pLanded" type="number" min="0"></div><div class="field"><label>STOCK INICIAL</label><input id="pStock" type="number" min="0" value="0"></div><div class="field"><label>PRECIO REFERENCIA</label><input id="pMarket" type="number" min="0" value="0"></div><div class="field full"><label>LINK DE ORIGEN</label><input id="pUrl" placeholder="https://…"></div></div>`,`<button class="ghost-btn" onclick="closeModal()">Cancelar</button><button class="primary-btn" onclick="saveProduct()">Guardar producto</button>`)}
function saveProduct(){const name=$('#pName').value.trim();if(!name)return toast('Escribe el nombre del producto');state.products.unshift({id:`PRD-${String(state.products.length+1).padStart(4,'0')}`,name,emoji:'📦',source:$('#pSource').value,sourceUrl:$('#pUrl').value,cost:+$('#pCost').value||0,landed:+$('#pLanded').value||0,stock:+$('#pStock').value||0,reserved:0,marketPrice:+$('#pMarket').value||0,status:(+$('#pStock').value||0)>5?'En stock':'Stock bajo',category:$('#pCat').value||'General',comparisons:[]});closeModal();renderProducts();toast('Producto creado')}
function addComparison(id){const p=state.products.find(x=>x.id===id);showModal('Agregar referencia manual',p.name,`<div class="form-grid"><div class="field"><label>FUENTE / TIENDA</label><input id="cSource" placeholder="Soriana, Walmart, tienda local…"></div><div class="field"><label>PRECIO VISTO</label><input id="cPrice" type="number" min="0"></div><div class="field full"><label>LINK (OPCIONAL)</label><input id="cUrl" placeholder="https://…"></div><div class="field full"><label>NOTA</label><textarea id="cNote" placeholder="Ej. Parece el mismo modelo pero incluye menos accesorios"></textarea></div></div>`,`<button class="ghost-btn" onclick="openProduct('${id}')">Volver</button><button class="primary-btn" onclick="saveComparison('${id}')">Guardar referencia</button>`)}
function saveComparison(id){const p=state.products.find(x=>x.id===id),source=$('#cSource').value.trim(),price=+$('#cPrice').value;if(!source||!price)return toast('Completa fuente y precio');p.comparisons.push({source,price,url:$('#cUrl').value||'#',date:today,mode:'Manual'});p.marketPrice=Math.round(p.comparisons.reduce((a,c)=>a+c.price,0)/p.comparisons.length);openProduct(id);toast('Referencia agregada')}
function fakeAISearch(id){toast('La búsqueda IA todavía no está conectada; puedes agregar una referencia manual')}
function prepareMarketplace(id){const p=state.products.find(x=>x.id===id),price=p.marketPrice?Math.max(p.landed+50,Math.round(p.marketPrice*.92/10)*10):p.landed*1.6;const description=`${p.name}\n\nProducto nuevo y disponible para entrega.\n✅ Stock: ${p.stock-p.reserved} unidades\n✅ Revisión antes de entrega\n✅ Pregunta por disponibilidad y opciones de entrega\n\nPrecio: ${MXN.format(price)}`;showModal('Preparar Facebook Marketplace','Revisa todo antes de abrir Marketplace',`<div class="callout">La app prepara la publicación, pero tú confirmas manualmente lo que se va a subir. No se publica nada sin tu revisión.</div><div class="separator"></div><div class="form-grid"><div class="field full"><label>TÍTULO</label><input id="mTitle" value="${escapeHtml(p.name)}"></div><div class="field"><label>PRECIO</label><input id="mPrice" type="number" value="${price}"></div><div class="field"><label>CONDICIÓN</label><select><option>Nuevo</option><option>Usado - como nuevo</option></select></div><div class="field full"><label>DESCRIPCIÓN</label><textarea id="mDesc" style="min-height:150px">${escapeHtml(description)}</textarea></div></div><div class="photo-strip"><div class="photo-box">📷</div><div class="photo-box">📷</div><div class="photo-box">＋</div></div><div class="checklist"><label class="check"><input type="checkbox" checked> Fotos correctas</label><label class="check"><input type="checkbox" checked> Precio confirmado</label><label class="check"><input type="checkbox" checked> Stock disponible</label><label class="check"><input type="checkbox"> Descripción revisada</label></div>`,`<button class="ghost-btn" onclick="copyMarketplace()">Copiar datos</button><button class="primary-btn" onclick="openMarketplace()">Abrir Marketplace ↗</button>`)}
function copyMarketplace(){const text=`${$('#mTitle').value}\n${MXN.format(+$('#mPrice').value)}\n\n${$('#mDesc').value}`;navigator.clipboard?.writeText(text);toast('Publicación copiada al portapapeles')}
function openMarketplace(){window.open('https://www.facebook.com/marketplace/create/item','_blank');toast('Marketplace abierto; revisa y publica manualmente')}

function renderIdeas(){const stages=['Nueva','Investigación','Votación','Aprobada'];$('#content').innerHTML=`<div class="toolbar"><div><button class="primary-btn" id="ideaAdd">＋ Proponer producto</button></div><div class="filters"><span class="badge blue">${state.ideas.length} propuestas</span></div></div><div class="kanban">${stages.map(st=>`<div class="kanban-col"><div class="kanban-title"><span>${st}</span><span class="badge">${state.ideas.filter(i=>i.stage===st).length}</span></div>${state.ideas.filter(i=>i.stage===st).map(i=>`<div class="idea-card"><h3>${i.name}</h3><p>${i.detail}</p><div class="idea-meta"><span>${i.id}</span><strong>👍 ${i.votes.yes} · 🤔 ${i.votes.maybe} · 👎 ${i.votes.no}</strong></div><div class="vote-row"><button class="vote-btn" onclick="voteIdea('${i.id}','yes')">👍 Comprar</button><button class="vote-btn" onclick="voteIdea('${i.id}','maybe')">🤔 Duda</button><button class="vote-btn" onclick="voteIdea('${i.id}','no')">👎 No</button></div></div>`).join('')||`<div class="empty" style="padding:25px 8px">Sin propuestas</div>`}</div>`).join('')}</div>`;$('#ideaAdd').onclick=openIdea}
function openIdea(){showModal('Nueva idea','Cualquier socio puede proponer una inversión',`<div class="form-grid"><div class="field full"><label>PRODUCTO</label><input id="iName" placeholder="¿Qué encontraste?"></div><div class="field full"><label>LINK TEMU / ALIEXPRESS / OTRO</label><input id="iUrl" placeholder="https://…"></div><div class="field"><label>COSTO APROX.</label><input id="iCost" type="number"></div><div class="field"><label>PRECIO DE VENTA ESTIMADO</label><input id="iSell" type="number"></div><div class="field full"><label>¿POR QUÉ LO PROPONES?</label><textarea id="iWhy"></textarea></div></div><div class="callout" style="margin-top:14px">Después podrás pedir a la IA que busque similares en Amazon, Mercado Libre u otras fuentes, o agregar referencias manuales.</div>`,`<button class="ghost-btn" onclick="closeModal()">Cancelar</button><button class="primary-btn" onclick="saveIdea()">Crear propuesta</button>`)}
function saveIdea(){const name=$('#iName').value.trim();if(!name)return toast('Escribe el producto');state.ideas.unshift({id:`IDE-${String(state.ideas.length+15).padStart(4,'0')}`,name,detail:`Costo aprox. ${MXN.format(+$('#iCost').value||0)} · venta ${MXN.format(+$('#iSell').value||0)}`,stage:'Nueva',votes:{yes:0,maybe:0,no:0}});closeModal();renderIdeas();toast('Propuesta creada')}
function voteIdea(id,type){state.ideas.find(i=>i.id===id).votes[type]++;renderIdeas();toast('Voto registrado')}

function renderPurchases(){const rows=[{id:'COM-0008',provider:'AliExpress',items:'Selladora térmica mini USB',qty:30,total:2370,status:'En tránsito',eta:'08 oct'},{id:'COM-0007',provider:'Temu',items:'Lámpara LED recargable',qty:25,total:2900,status:'Recibida',eta:'—'},{id:'COM-0006',provider:'AliExpress',items:'Organizador cajuela',qty:10,total:1390,status:'Recibida',eta:'—'}];$('#content').innerHTML=`<div class="toolbar"><button class="primary-btn" onclick="toast('Formulario de compra preparado para siguiente iteración')">＋ Registrar compra</button><div class="filters"><span class="badge blue">🚢 1 en tránsito</span></div></div><div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Folio</th><th>Proveedor</th><th>Producto</th><th>Cantidad</th><th>Total</th><th>Estado</th><th>ETA</th></tr></thead><tbody>${rows.map(r=>`<tr><td><strong>${r.id}</strong></td><td>${r.provider}</td><td>${r.items}</td><td>${r.qty}</td><td>${MXN.format(r.total)}</td><td><span class="badge ${r.status==='Recibida'?'green':'blue'}">${r.status}</span></td><td>${r.eta}</td></tr>`).join('')}</tbody></table></div></div>`}
function renderSales(){const total=state.sales.reduce((a,s)=>a+s.price,0),net=state.sales.reduce((a,s)=>a+businessProfit(s),0),comm=state.sales.reduce((a,s)=>a+sellerCommission(s),0);$('#content').innerHTML=`<div class="grid metrics">${metric('Venta bruta',MXN.format(total),'💵','Suma de precios reales')}${metric('Gastos directos',MXN.format(state.sales.reduce((a,s)=>a+s.shipping+s.platformFee+s.other,0)),'🚚','Flete + plataforma + extras')}${metric('Comisiones equipo',MXN.format(comm),'👥','Acumulado por reglas')}${metric('Utilidad negocio',MXN.format(net),'↗','Después de comisión vendedor',true)}</div><div class="section-head"><div><h2>Registro de ventas</h2><p>Cada venta conserva su precio, canal y costos reales.</p></div><button class="primary-btn" onclick="openSale()">＋ Registrar venta</button></div><div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Venta</th><th>Producto</th><th>Vendedor / Canal</th><th>Precio</th><th>Gastos</th><th>Utilidad antes comisión</th><th>Comisión vendedor</th><th>Negocio</th></tr></thead><tbody>${state.sales.map(s=>`<tr><td><strong>${s.id}</strong><div style="font-size:10px;color:var(--muted)">${s.date}</div></td><td>${s.product}</td><td><strong>${s.seller}</strong><div style="font-size:10px;color:var(--muted)">${s.channel}</div></td><td>${MXN.format(s.price)}</td><td>${MXN.format(s.shipping+s.platformFee+s.other)}</td><td>${MXN.format(profit(s))}</td><td class="money">${MXN.format(sellerCommission(s))}</td><td class="money positive">${MXN.format(businessProfit(s))}</td></tr>`).join('')}</tbody></table></div></div>`}
function openSale(productId=''){const p=state.products.find(x=>x.id===productId);showModal('Registrar venta','Captura lo que realmente ocurrió',`<div class="form-grid"><div class="field full"><label>PRODUCTO</label><select id="sProduct">${state.products.map(x=>`<option value="${x.id}" ${p?.id===x.id?'selected':''}>${x.name}</option>`).join('')}</select></div><div class="field"><label>VENDEDOR</label><select id="sSeller">${state.members.map(m=>`<option>${m.name}</option>`).join('')}</select></div><div class="field"><label>CANAL</label><select id="sChannel"><option>Facebook Marketplace</option><option>Venta física</option><option>Instagram</option><option>WhatsApp</option><option>Otra plataforma</option></select></div><div class="field"><label>PRECIO REAL DE VENTA</label><input id="sPrice" type="number" value="${p?.marketPrice||0}"></div><div class="field"><label>FLETE PAGADO POR NOSOTROS</label><input id="sShip" type="number" value="0"></div><div class="field"><label>COMISIÓN DE PLATAFORMA</label><input id="sFee" type="number" value="0"></div><div class="field"><label>OTROS COSTOS / DESCUENTOS</label><input id="sOther" type="number" value="0"></div><div class="field"><label>% COMISIÓN VENDEDOR</label><input id="sPct" type="number" value="${state.settings.defaultSellerPct}"></div><div class="field full"><label>NOTA</label><textarea placeholder="Ej. Se entregó en persona; cliente pagó transferencia"></textarea></div></div>`,`<button class="ghost-btn" onclick="closeModal()">Cancelar</button><button class="primary-btn" onclick="saveSale()">Registrar venta</button>`)}
function saveSale(){const p=state.products.find(x=>x.id===$('#sProduct').value);const s={id:`VEN-${String(state.sales.length+8).padStart(4,'0')}`,date:today,product:p.name,seller:$('#sSeller').value,channel:$('#sChannel').value,price:+$('#sPrice').value||0,cost:p.landed,shipping:+$('#sShip').value||0,platformFee:+$('#sFee').value||0,other:+$('#sOther').value||0,sellerPct:+$('#sPct').value||0};state.sales.unshift(s);if(p.stock>0)p.stock--;closeModal();go('sales');toast(`Venta ${s.id} registrada`) }
function renderTeam(){const rows=state.members.map(m=>{const mine=state.sales.filter(s=>s.seller===m.name);return {m,count:mine.length,revenue:mine.reduce((a,s)=>a+s.price,0),generated:mine.reduce((a,s)=>a+profit(s),0),due:mine.reduce((a,s)=>a+sellerCommission(s),0)}});$('#content').innerHTML=`<div class="callout">“Producido” y “le corresponde” son conceptos separados: la app conserva venta bruta, utilidad generada y comisión personal.</div><div class="section-head"><div><h2>Balance del equipo</h2><p>Acumulado trazable venta por venta.</p></div><button class="ghost-btn" onclick="toast('Aquí agregaremos aportaciones, retiros y pagos de balance')">Registrar pago</button></div><div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Persona</th><th>Rol</th><th>Ventas</th><th>Venta total</th><th>Utilidad generada</th><th>Le corresponde</th></tr></thead><tbody>${rows.map(r=>`<tr><td><div class="product-cell"><div class="avatar">${r.m.name.slice(0,2).toUpperCase()}</div><div><strong>${r.m.name}</strong><span>Socio activo</span></div></div></td><td>${r.m.role}</td><td>${r.count}</td><td>${MXN.format(r.revenue)}</td><td>${MXN.format(r.generated)}</td><td class="money positive">${MXN.format(r.due)}</td></tr>`).join('')}</tbody></table></div></div>`}
function renderSettings(){$('#content').innerHTML=`<div class="grid two-col"><div class="card card-pad"><h2 style="margin-top:0;font-size:16px">Inteligencia artificial (próximamente)</h2><p style="color:var(--muted);font-size:12px">La búsqueda IA todavía no está conectada. Configuraremos un backend seguro antes de aceptar claves.</p><div class="form-grid"><div class="field"><label>PROVEEDOR</label><select id="aiProvider" disabled><option>OpenAI</option><option>Google Gemini</option><option>Anthropic</option><option>OpenRouter</option><option>Compatible OpenAI</option></select></div><div class="field"><label>MODELO</label><input id="aiModel" disabled placeholder="Próximamente"></div><div class="field full"><label>API KEY</label><input type="password" disabled placeholder="Próximamente: backend seguro"><span class="helper">No pegues aquí ninguna clave real.</span></div></div></div><div class="card card-pad"><h2 style="margin-top:0;font-size:16px">Reglas de venta</h2><div class="field"><label>COMISIÓN PREDETERMINADA DEL VENDEDOR (%)</label><input id="defaultPct" type="number" value="${state.settings.defaultSellerPct}"></div><div class="separator"></div><h2 style="font-size:16px">Fuentes sugeridas</h2><p style="font-size:12px;color:var(--muted)">Puedes agregar referencias manuales por producto. Estas casillas son una vista previa.</p><div class="checklist"><label class="check"><input type="checkbox" disabled checked> Amazon</label><label class="check"><input type="checkbox" disabled checked> Mercado Libre</label><label class="check"><input type="checkbox" disabled> Walmart</label><label class="check"><input type="checkbox" disabled> Soriana</label></div></div></div>`;$('#defaultPct').onchange=e=>state.settings.defaultSellerPct=+e.target.value||0}

function showModal(title,sub,body,footer=`<button class="primary-btn" onclick="closeModal()">Cerrar</button>`){$('#modalRoot').innerHTML=`<div class="modal-backdrop" id="modalBackdrop"><div class="modal"><div class="modal-head"><div><h2>${title}</h2><p>${sub||''}</p></div><button class="close-btn" onclick="closeModal()">×</button></div><div class="modal-body">${body}</div><div class="modal-foot">${footer}</div></div></div>`;$('#modalBackdrop').onclick=e=>{if(e.target.id==='modalBackdrop')closeModal()}}
function closeModal(){$('#modalRoot').innerHTML=''} function toast(msg){const t=el('div','toast');t.textContent=msg;$('#toastRoot').appendChild(t);setTimeout(()=>t.remove(),2600)}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}

$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');$('#quickIdeaBtn').onclick=openIdea;$('#quickProductBtn').onclick=openAddProduct;
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
render();
