import './style.css';
import {connectFirebase} from './firebase.js';
import {onAuthStateChanged,signInWithEmailAndPassword,createUserWithEmailAndPassword,sendEmailVerification,signOut,GoogleAuthProvider,signInWithPopup,sendPasswordResetEmail} from 'firebase/auth';
import {collection,doc,getDoc,getDocs,setDoc,addDoc,updateDoc,onSnapshot,query,where,runTransaction,writeBatch,serverTimestamp,increment} from 'firebase/firestore';
import {jsPDF} from 'jspdf';

const app=document.querySelector('#app');
const money=new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'});
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl=v=>{try{const u=new URL(v);return ['http:','https:'].includes(u.protocol)?u.href:'';}catch{return '';}};
const iso=()=>new Date().toLocaleDateString('en-CA',{timeZone:'America/Monterrey'});
const uid=()=>crypto.randomUUID();
const num=v=>Math.round((Number(v)||0)*100)/100;
const dateOf=v=>v?.date||'';
const model={page:'dashboard',month:iso().slice(0,7),data:{products:[],ideas:[],purchases:[],sales:[],payments:[],members:[],invites:[],movements:[]},user:null,workspace:null,role:null,auth:null,db:null,unsubs:[],busy:false};
const col=name=>collection(model.db,'workspaces',model.workspace,name);
const ref=(name,id)=>doc(model.db,'workspaces',model.workspace,name,id);
const can=(...roles)=>roles.includes(model.role)||model.role==='admin';
const err=e=>{console.error(e);alert(({'auth/invalid-credential':'Correo o contraseña incorrectos.','auth/email-already-in-use':'Ese correo ya está registrado.','auth/operation-not-allowed':'Activa el método de ingreso en Firebase Authentication.','permission-denied':'No tienes permiso para esta operación. Revisa tu invitación y las reglas publicadas.'})[e?.code]||e?.message||'Ocurrió un error.');};
function view(html){app.innerHTML=html;}
function card(label,value,subtitle=''){return `<div class="metric"><small>${esc(label)}</small><strong>${esc(value)}</strong><span>${esc(subtitle)}</span></div>`;}
function empty(text){return `<div class="empty">${esc(text)}</div>`;}
function button(label,action,kind=''){return `<button class="${kind}" data-action="${action}">${label}</button>`;}
function period(a){return !model.month || dateOf(a).slice(0,7)===model.month;}
function profit(s){return num(s.price)-num(s.cost)-num(s.shipping)-num(s.fee)-num(s.other);}
function commission(s){return Math.max(0,profit(s))*num(s.pct)/100;}
function pageTitle(){return ({dashboard:'Resumen',products:'Productos e inventario',ideas:'Ideas y votación',purchases:'Compras y recepción',sales:'Ventas reales',team:'Equipo y balances',reports:'Reportes',settings:'Configuración'})[model.page];}
const nav=[['dashboard','◫','Resumen'],['products','▦','Productos'],['ideas','✦','Ideas'],['purchases','⇢','Compras'],['sales','＄','Ventas'],['team','♧','Equipo'],['reports','▤','Reportes'],['settings','⚙','Ajustes']];
function render(){
 if(!model.workspace)return;
 const name=model.data.members.find(x=>x.id===model.user.uid)?.name||model.user.email;
 const activeModal=document.querySelector('#modal')?.firstElementChild;
 view(`<div class="shell"><aside><div class="logo"><span>中</span><div><b>Productos China</b><small>${esc(model.workspace)}</small></div></div><nav>${nav.map(([id,icon,title])=>`<button data-page="${id}" class="${model.page===id?'on':''}"><span>${icon}</span>${title}</button>`).join('')}</nav><div class="account"><b>${esc(name)}</b><small>${esc(model.role||'Socio')} · ${esc(model.user.email)}</small>${button('Cerrar sesión','logout','plain')}</div></aside><main><header><div><small class="kicker">OPERACIÓN · ${esc(model.month||'TODOS LOS PERIODOS')}</small><h1>${pageTitle()}</h1></div><div class="header-actions"><label>Periodo <input type="month" id="period" value="${esc(model.month)}"></label>${button('Exportar','export-menu','secondary')}</div></header><section>${({dashboard:dashboard,products:products,ideas:ideas,purchases:purchases,sales:sales,team:team,reports:reports,settings:settings})[model.page]()}</section></main></div><div class="mobile-nav">${nav.slice(0,5).map(([id,icon,title])=>`<button data-page="${id}" class="${model.page===id?'on':''}">${icon}<small>${title}</small></button>`).join('')}</div><div id="modal"></div>`);
 if(activeModal)document.querySelector('#modal').append(activeModal);
 document.querySelector('#period').onchange=e=>{model.month=e.target.value;render();};
}
function dashboard(){const s=model.data.sales.filter(period),p=model.data.products,margin=s.reduce((a,x)=>a+profit(x)-commission(x),0),revenue=s.reduce((a,x)=>a+num(x.price),0),stock=p.reduce((a,x)=>a+num(x.stock),0);
 return `<div class="metrics">${card('Ventas del mes',money.format(revenue),`${s.length} operaciones`)}${card('Utilidad del negocio',money.format(margin),'Después de gastos y vendedores')}${card('Existencia',`${stock} unidades`,`${p.length} productos`)}${card('Ideas por evaluar',model.data.ideas.filter(x=>x.status!=='Aprobada').length,'Decisiones del equipo')}</div><div class="twocol"><div class="panel"><div class="section-title"><h2>Actividad reciente</h2>${can('ventas')?button('Registrar venta','new-sale','primary'):''}</div>${s.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5).map(x=>`<div class="row"><div><b>${esc(x.productName)}</b><small>${esc(x.date)} · ${esc(x.sellerName)} · ${esc(x.channel)}</small></div><b>${money.format(x.price)}</b></div>`).join('')||empty('Aquí aparecerán las primeras ventas.')}</div><div class="panel"><div class="section-title"><h2>Por atender</h2>${can('compras','almacen')?button('Nuevo producto','new-product','secondary'):''}</div>${p.filter(x=>num(x.stock)<=num(x.minStock||3)).slice(0,5).map(x=>`<div class="row"><div><b>${esc(x.name)}</b><small>Stock mínimo: ${esc(x.minStock||3)}</small></div><span class="tag warn">${esc(x.stock)} piezas</span></div>`).join('')||empty('El inventario está por encima de los mínimos.')}</div></div>`;
}
function products(){const p=model.data.products;return `<div class="section-title"><p>Una ficha por producto: costo, existencia, referencias y publicación.</p>${can('compras','almacen')?button('＋ Producto','new-product','primary'):''}</div><div class="cards">${p.map(x=>`<article class="product panel"><div class="product-head"><div class="product-icon">${esc(x.emoji||'📦')}</div><div><small>${esc(x.sku||x.id.slice(0,8))} · ${esc(x.category||'General')}</small><h3>${esc(x.name)}</h3></div></div><div class="facts"><span>Costo <b>${money.format(x.cost)}</b></span><span>Stock <b>${esc(x.stock)}</b></span><span>Referencias <b>${(x.comparisons||[]).length}</b></span></div><div class="actions">${button('Abrir ficha',`product:${x.id}`,'secondary')}${can('ventas')?button('Vender',`sale:${x.id}`,'primary'):''}</div></article>`).join('')||empty('Agrega el primer producto para comenzar.')}</div>`;}
function ideas(){const rows=model.data.ideas.filter(period);return `<div class="section-title"><p>Propuestas del periodo seleccionado. Registra ideas y voten antes de comprar.</p>${button('＋ Proponer','new-idea','primary')}</div><div class="cards">${rows.map(x=>`<article class="panel"><small>${esc(x.date)} · ${esc(x.status||'Nueva')}</small><h3>${esc(x.name)}</h3><p>${esc(x.notes||'Sin notas')}</p><p>Proveedor: ${esc(x.url||'Por definir')}</p><div class="facts"><span>Costo <b>${money.format(x.cost)}</b></span><span>Venta estimada <b>${money.format(x.target)}</b></span></div><div class="actions">${['Comprar','Investigar','No comprar'].map(v=>button(`${v} (${Object.values(x.votes||{}).filter(y=>y===v).length})`,`vote:${x.id}:${v}`,'secondary')).join('')}${can('compras')?button('Crear compra',`buy-idea:${x.id}`,'plain'):''}</div></article>`).join('')||empty('No hay propuestas en este periodo.')}</div>`;}
function purchases(){const rows=model.data.purchases.filter(period);return `<div class="section-title"><p>Compras del periodo seleccionado. Al recibirlas se suman las piezas al inventario.</p>${can('compras')?button('＋ Compra','new-purchase','primary'):''}</div><div class="panel table-wrap"><table><thead><tr><th>Fecha / folio</th><th>Producto</th><th>Proveedor</th><th>Cantidad</th><th>Total</th><th>Estado</th><th></th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.date)}<small>${esc(x.id.slice(0,8))}</small></td><td>${esc(x.productName)}</td><td>${esc(x.supplier)}</td><td>${esc(x.qty)}</td><td>${money.format(x.total)}</td><td><span class="tag">${esc(x.status)}</span></td><td>${x.status==='En tránsito'&&can('compras','almacen')?button('Recibir',`receive:${x.id}`,'secondary'):''}</td></tr>`).join('')}</tbody></table>${rows.length?'':empty('Sin compras en este periodo.')}</div>`;}
function sales(){const s=model.data.sales.filter(period).slice().sort((a,b)=>b.date.localeCompare(a.date)),total=s.reduce((a,x)=>a+num(x.price),0),net=s.reduce((a,x)=>a+profit(x)-commission(x),0);return `<div class="metrics">${card('Ventas',money.format(total))}${card('Utilidad antes de vendedor',money.format(s.reduce((a,x)=>a+profit(x),0)))}${card('Comisiones de venta',money.format(s.reduce((a,x)=>a+commission(x),0)))}${card('Utilidad negocio',money.format(net))}</div><div class="section-title"><p>La venta guarda el precio real, el canal, el flete y la regla de comisión aplicada.</p>${can('ventas')?button('＋ Registrar venta','new-sale','primary'):''}</div><div class="panel table-wrap"><table><thead><tr><th>Fecha / folio</th><th>Producto</th><th>Vendedor · canal</th><th>Venta</th><th>Gastos</th><th>Comisión</th><th>Negocio</th></tr></thead><tbody>${s.map(x=>`<tr><td>${esc(x.date)}<small>${esc(x.id.slice(0,8))}</small></td><td>${esc(x.productName)}</td><td>${esc(x.sellerName)}<small>${esc(x.channel)}</small></td><td>${money.format(x.price)}</td><td>${money.format(num(x.shipping)+num(x.fee)+num(x.other))}</td><td>${money.format(commission(x))}</td><td><b>${money.format(profit(x)-commission(x))}</b></td></tr>`).join('')}</tbody></table>${s.length?'':empty('Sin ventas en este periodo.')}</div>`;}
function team(){const s=model.data.sales.filter(period),payments=model.data.payments.filter(period);return `<div class="section-title"><p>“Producido” y “le corresponde” se calculan por separado. Los pagos descuentan saldo.</p>${can('admin')?button('＋ Registrar pago','new-payment','primary'):''}</div><div class="panel table-wrap"><table><thead><tr><th>Integrante</th><th>Ventas</th><th>Ingreso generado</th><th>Utilidad generada</th><th>Comisión</th><th>Pagado</th><th>Saldo</th></tr></thead><tbody>${model.data.members.map(m=>{const mine=s.filter(x=>x.sellerId===m.id),due=mine.reduce((a,x)=>a+commission(x),0),paid=payments.filter(x=>x.memberId===m.id).reduce((a,x)=>a+num(x.amount),0);return `<tr><td><b>${esc(m.name)}</b><small>${esc(m.role)}</small></td><td>${mine.length}</td><td>${money.format(mine.reduce((a,x)=>a+num(x.price),0))}</td><td>${money.format(mine.reduce((a,x)=>a+profit(x),0))}</td><td>${money.format(due)}</td><td>${money.format(paid)}</td><td><b>${money.format(due-paid)}</b></td></tr>`;}).join('')}</tbody></table></div><div class="panel"><h3>Pagos registrados</h3>${payments.map(x=>`<div class="row"><span>${esc(x.date)} · ${esc(x.memberName)} · ${esc(x.note)}</span><b>${money.format(x.amount)}</b></div>`).join('')||empty('Sin pagos en este periodo.')}</div>`;}
function reports(){const kinds=[['sales','Ventas'],['products','Productos'],['purchases','Compras'],['ideas','Ideas'],['team','Balances'],['movements','Movimientos']];return `<div class="section-title"><p>Selecciona el mes arriba. Cada área se puede descargar en CSV o PDF y compartir desde el dispositivo.</p></div><div class="cards">${kinds.map(([kind,label])=>`<div class="panel"><h3>${label}</h3><div class="actions">${button('CSV',`csv-${kind}`,'secondary')}${button('PDF',`pdf-${kind}`,'primary')}${button('Compartir',`share-${kind}`,'secondary')}</div></div>`).join('')}</div><p class="muted">El envío se confirma en la aplicación que elijas; no se mandan correos automáticamente.</p>`;}
function settings(){const url=`${location.origin}/?join=${encodeURIComponent(model.workspace)}`;return `<div class="cards"><div class="panel"><h3>Equipo e invitaciones</h3><p>Invita por correo registrado y comparte el enlace. El invitado deberá confirmar su correo.</p>${can('admin')?`<form id="inviteForm" class="form-inline"><input name="email" type="email" placeholder="Correo de la persona" required><select name="role"><option value="socio">Socio</option><option value="ventas">Ventas</option><option value="compras">Compras</option><option value="almacen">Almacén</option><option value="admin">Administrador</option></select><button class="primary">Guardar invitación</button></form><label>Enlace de ingreso <input readonly value="${esc(url)}" id="inviteLink"></label>${button('Copiar enlace','copy-invite','secondary')}`:''}<h4>Miembros</h4>${model.data.members.map(x=>`<div class="row"><span>${esc(x.name)} · ${esc(x.email)}</span><span class="tag">${esc(x.role)}</span></div>`).join('')}</div><div class="panel"><h3>Comisiones</h3><p>Cada venta permite elegir el porcentaje exacto. La operación queda registrada con ese porcentaje; cambiar criterios futuros no modifica ventas previas.</p><p>Fuentes de comparación: cada producto permite agregar manualmente Amazon, Mercado Libre, Soriana o cualquier otra tienda, con precio, URL y fecha.</p><h3>IA bajo demanda</h3><p>La búsqueda con IA necesita un servicio de búsqueda web y un backend para guardar la clave de forma segura. De momento puedes abrir búsquedas públicas y capturar las referencias; ninguna clave se pega en el navegador.</p></div></div>`;}
function modal(title,body){const root=document.querySelector('#modal');root.innerHTML=`<div class="shade"><div class="dialog"><div class="section-title"><h2>${esc(title)}</h2><button data-action="close" class="plain" aria-label="Cerrar">✕</button></div>${body}</div></div>`;}
function field(label,name,type='text',value='',extra=''){return `<label>${esc(label)}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;}
function select(label,name,items,selected=''){return `<label>${esc(label)}<select name="${name}">${items.map(([value,text])=>`<option value="${esc(value)}" ${selected===value?'selected':''}>${esc(text)}</option>`).join('')}</select></label>`;}
function form(title,id,fields,action='Guardar'){modal(title,`<form id="${id}" class="fields">${fields}<div class="actions"><button type="button" class="secondary" data-action="close">Cancelar</button><button class="primary" type="submit">${action}</button></div></form>`);}
function productDetail(id){const p=model.data.products.find(x=>x.id===id);if(!p)return;const cs=p.comparisons||[];modal(p.name,`<p class="muted">${esc(p.sku||p.id)} · ${esc(p.category||'General')} · ${esc(p.supplier||'Sin proveedor')}</p><div class="metrics">${card('Existencia',p.stock)}${card('Costo real',money.format(p.cost))}${card('Precio sugerido',money.format(p.target))}</div><div class="section-title"><h3>Referencias de mercado</h3>${can('compras','ventas')?button('＋ Comparación',`comparison:${id}`,'secondary'):''}</div>${cs.map(c=>`<div class="row"><div><b>${esc(c.source)}</b><small>${esc(c.date)} · ${esc(c.mode||'Manual')}</small></div><div><b>${money.format(c.price)}</b> ${c.url?`<a href="${esc(safeUrl(c.url))}" rel="noopener noreferrer" target="_blank">Abrir ↗</a>`:''}</div></div>`).join('')||empty('Agrega una referencia manual cuando la confirmes.')}<div class="actions">${button('Buscar Amazon',`search:${id}:amazon`,'secondary')}${button('Buscar Mercado Libre',`search:${id}:ml`,'secondary')}${button('Preparar Marketplace',`market:${id}`,'primary')}${can('compras','almacen')?button('Ajustar stock',`stock:${id}`,'secondary'):''}</div>`);}
function marketplace(id){const p=model.data.products.find(x=>x.id===id);const text=`${p.name}\n\nProducto nuevo. ${p.notes||''}\nEntrega a convenir.`;form('Revisar publicación para Marketplace','marketForm',`${field('Título','title','text',p.name,'required')}${field('Precio','price','number',p.target||0,'min="0" required')}<label>Descripción<textarea name="description" rows="5">${esc(text)}</textarea></label>${field('Categoría','category','text',p.category||'')}${select('Condición','condition',[['Nuevo','Nuevo'],['Usado','Usado']])}<p class="muted">Revisa título, precio, fotos y stock en Facebook antes de pulsar Publicar allí. El navegador no puede llenar ni subir fotos automáticamente en Marketplace.</p><div class="actions"><button type="button" data-action="copy-market" class="secondary">Copiar datos</button><button type="button" data-action="open-market" class="primary">Abrir Marketplace ↗</button></div>`,'Cerrar');}
async function saveMovement(kind,productId,qty,note){await addDoc(col('movements'),{date:iso(),kind,productId,qty,note,by:model.user.uid,createdAt:serverTimestamp()});}
function action(a){if(a==='close'){document.querySelector('#modal').innerHTML='';return;}
 if(a==='logout')return signOut(model.auth).catch(err);
 if(a==='export-menu'){model.page='reports';render();return;}
 if(a==='new-product')return form('Nuevo producto','productForm',`${field('Nombre','name','text','','required')}${field('SKU o clave','sku')}${field('Categoría','category')}${field('Proveedor','supplier')}${field('URL proveedor','url','url')}${field('Costo real unitario MXN','cost','number','0','min="0" step="0.01" required')}${field('Precio objetivo MXN','target','number','0','min="0" step="0.01"')}${field('Stock inicial','stock','number','0','min="0" step="1"')}${field('Stock mínimo','minStock','number','3','min="0" step="1"')}`);
 if(a==='new-idea')return form('Proponer producto','ideaForm',`${field('Producto','name','text','','required')}${field('Enlace proveedor','url','url')}${field('Costo estimado MXN','cost','number','0','min="0" step="0.01"')}${field('Precio objetivo MXN','target','number','0','min="0" step="0.01"')}<label>Motivo o notas<textarea name="notes"></textarea></label>`);
 if(a==='new-purchase'||a.startsWith('buy-idea:')){let idea=a.startsWith('buy-idea:')?model.data.ideas.find(x=>x.id===a.slice(9)):null;return form('Registrar compra','purchaseForm',`${select('Producto','productId',model.data.products.map(x=>[x.id,x.name]))}${field('Proveedor','supplier','text','','required')}${field('Cantidad','qty','number','1','min="1" step="1" required')}${field('Total pagado MXN','total','number','0','min="0" step="0.01" required')}${field('Fecha estimada de llegada','eta','date')}`);}
 if(a==='new-sale'||a.startsWith('sale:')){const pid=a.startsWith('sale:')?a.slice(5):'';return form('Registrar venta real','saleForm',`${select('Producto','productId',model.data.products.map(x=>[x.id,`${x.name} · ${x.stock} disponibles`]),pid)}${select('Vendedor','sellerId',model.data.members.map(x=>[x.id,x.name]),model.user.uid)}${select('Canal','channel',['Facebook Marketplace','Venta física','WhatsApp','Instagram','Otra plataforma','Recomendación'].map(x=>[x,x]))}${field('Precio real cobrado MXN','price','number',model.data.products.find(x=>x.id===(pid||model.data.products[0]?.id))?.target||0,'min="0" step="0.01" required')}${field('Flete pagado por el negocio MXN','shipping','number','0','min="0" step="0.01"')}${field('Comisión de plataforma MXN','fee','number','0','min="0" step="0.01"')}${field('Otros costos del negocio MXN (precio ya con descuento)','other','number','0','min="0" step="0.01"')}${field('Comisión del vendedor % de utilidad','pct','number','20','min="0" max="100" step="0.01"')}<label>Nota<textarea name="notes"></textarea></label>`);}
 if(a==='new-payment')return form('Registrar pago de comisión','paymentForm',`${select('Integrante','memberId',model.data.members.map(x=>[x.id,x.name]))}${field('Monto pagado MXN','amount','number','0','min="0.01" step="0.01" required')}${field('Nota / medio de pago','note')}`);
 if(a.startsWith('product:'))return productDetail(a.slice(8));
 if(a.startsWith('market:'))return marketplace(a.slice(7));
 if(a.startsWith('comparison:')){window.currentProduct=a.slice(11);return form('Nueva referencia de mercado','comparisonForm',`${field('Fuente (Amazon, Soriana, etc.)','source','text','','required')}${field('Precio MXN','price','number','0','min="0" step="0.01" required')}${field('URL de la publicación','url','url')}${field('Fecha de consulta','date','date',iso(),'required')}`);}
 if(a.startsWith('search:')){const [,id,site]=a.split(':'),p=model.data.products.find(x=>x.id===id);window.open((site==='amazon'?'https://www.google.com/search?q=site%3Aamazon.com.mx+':'https://www.google.com/search?q=site%3Amercadolibre.com.mx+')+encodeURIComponent(p.name),'_blank','noopener');return;}
 if(a.startsWith('stock:')){window.currentProduct=a.slice(6);return form('Ajustar inventario','stockForm',`${field('Unidades (+ entrada, - salida)','delta','number','0','step="1" required')}${field('Motivo','note','text','','required')}`);}
 if(a.startsWith('receive:'))return receive(a.slice(8));
 if(a.startsWith('vote:')){const [,id,vote]=a.split(':');return voteIdea(id,vote);}
 if(a==='copy-invite')return navigator.clipboard.writeText(document.querySelector('#inviteLink').value).then(()=>alert('Enlace copiado.')).catch(err);
 if(a==='copy-market'){const f=document.querySelector('#marketForm'),d=new FormData(f);return navigator.clipboard.writeText(`${d.get('title')}\n$${d.get('price')}\n${d.get('condition')} · ${d.get('category')}\n\n${d.get('description')}`).then(()=>alert('Texto copiado. Revisa las fotos en Facebook.')).catch(err);}
 if(a==='open-market'){window.open('https://www.facebook.com/marketplace/create/item','_blank','noopener');return;}
 if(a.startsWith('csv-'))return exportCsv(a.slice(4));
 if(a.startsWith('pdf-'))return exportPdf(a.slice(4));
 if(a.startsWith('share-'))return share(a.slice(6));
}
async function voteIdea(id,vote){try{const r=ref('ideas',id);await runTransaction(model.db,async tx=>{const d=await tx.get(r);if(!d.exists())throw Error('Propuesta no encontrada');tx.update(r,{[`votes.${model.user.uid}`]:vote});});}catch(e){err(e);}}
async function receive(id){try{const pr=ref('purchases',id),purchase=model.data.purchases.find(x=>x.id===id),product=ref('products',purchase.productId);await runTransaction(model.db,async tx=>{const [a,b]=await Promise.all([tx.get(pr),tx.get(product)]);if(a.data()?.status!=='En tránsito')throw Error('Esta compra ya se recibió.');if(!b.exists())throw Error('Producto no encontrado');tx.update(pr,{status:'Recibida',receivedAt:serverTimestamp()});tx.update(product,{stock:increment(a.data().qty)});tx.set(ref('movements',uid()),{date:iso(),kind:'Entrada por compra',productId:purchase.productId,qty:purchase.qty,note:`Compra ${id}`,by:model.user.uid,createdAt:serverTimestamp()});});alert('Compra recibida; inventario actualizado.');}catch(e){err(e);}}
async function submit(e){const f=e.target;if(!(f instanceof HTMLFormElement))return;e.preventDefault();if(model.busy)return;model.busy=true;const d=Object.fromEntries(new FormData(f));const v=(name)=>num(d[name]);try{
 if(f.id==='loginForm')await signInWithEmailAndPassword(model.auth,d.email.trim(),d.password);
 if(f.id==='registerForm'){const u=await createUserWithEmailAndPassword(model.auth,d.email.trim(),d.password);await sendEmailVerification(u.user);alert('Te enviamos un enlace de verificación. Confirma tu correo y vuelve a ingresar.');}
 if(f.id==='workspaceForm'){const w=uid(),wref=doc(model.db,'workspaces',w);await setDoc(wref,{ownerUid:model.user.uid,name:d.name.trim(),createdAt:serverTimestamp()});await setDoc(doc(wref,'members',model.user.uid),{name:d.memberName.trim(),email:model.user.email.toLowerCase(),role:'admin',joinedAt:serverTimestamp()});await setDoc(doc(model.db,'profiles',model.user.uid),{workspaceId:w},{merge:true});await attach(w);}
 if(f.id==='joinForm'){const w=d.workspaceId.trim(),email=model.user.email.toLowerCase(),invite=await getDoc(doc(model.db,'workspaces',w,'invites',email));if(!invite.exists())throw Error('No hay una invitación para este correo en ese equipo.');await setDoc(doc(model.db,'workspaces',w,'members',model.user.uid),{name:d.name.trim(),email,role:invite.data().role,joinedAt:serverTimestamp()});await setDoc(doc(model.db,'profiles',model.user.uid),{workspaceId:w},{merge:true});await attach(w);}
 if(f.id==='inviteForm'){await setDoc(ref('invites',d.email.trim().toLowerCase()),{role:d.role,createdAt:serverTimestamp()});alert('Invitación guardada. Comparte el enlace con esa persona.');}
 if(f.id==='productForm'){const id=uid(),batch=writeBatch(model.db);batch.set(ref('products',id),{name:d.name.trim(),sku:d.sku.trim(),category:d.category.trim(),supplier:d.supplier.trim(),url:d.url.trim(),cost:v('cost'),target:v('target'),stock:Math.floor(v('stock')),minStock:Math.floor(v('minStock')),comparisons:[],date:iso(),createdBy:model.user.uid,createdAt:serverTimestamp()});if(v('stock'))batch.set(ref('movements',uid()),{date:iso(),kind:'Existencia inicial',productId:id,qty:v('stock'),note:'Alta de producto',by:model.user.uid,createdAt:serverTimestamp()});await batch.commit();}
 if(f.id==='ideaForm')await addDoc(col('ideas'),{name:d.name.trim(),url:d.url.trim(),cost:v('cost'),target:v('target'),notes:d.notes.trim(),votes:{},status:'Nueva',date:iso(),createdBy:model.user.uid,createdAt:serverTimestamp()});
 if(f.id==='purchaseForm'){const p=model.data.products.find(x=>x.id===d.productId);if(!p)throw Error('Primero registra un producto.');await addDoc(col('purchases'),{productId:p.id,productName:p.name,supplier:d.supplier.trim(),qty:Math.floor(v('qty')),total:v('total'),eta:d.eta||'',status:'En tránsito',date:iso(),createdBy:model.user.uid,createdAt:serverTimestamp()});}
 if(f.id==='saleForm'){const p=model.data.products.find(x=>x.id===d.productId),m=model.data.members.find(x=>x.id===d.sellerId);if(!p||!m)throw Error('Selecciona un producto y un vendedor.');if([d.price,d.shipping,d.fee,d.other,d.pct].some(x=>num(x)<0)||v('pct')>100)throw Error('Revisa los importes y el porcentaje.');const saleId=uid(),productRef=ref('products',p.id);await runTransaction(model.db,async tx=>{const snap=await tx.get(productRef);if(!snap.exists()||snap.data().stock<1)throw Error('No hay existencia disponible para esta venta.');tx.update(productRef,{stock:increment(-1)});tx.set(ref('movements',uid()),{date:iso(),kind:'Venta',productId:p.id,qty:-1,note:`Venta ${saleId}`,by:model.user.uid,createdAt:serverTimestamp()});tx.set(ref('sales',saleId),{productId:p.id,productName:p.name,sellerId:m.id,sellerName:m.name,channel:d.channel,price:v('price'),cost:num(snap.data().cost),shipping:v('shipping'),fee:v('fee'),other:v('other'),pct:v('pct'),notes:d.notes.trim(),qty:1,date:iso(),createdBy:model.user.uid,createdAt:serverTimestamp()});});}
 if(f.id==='paymentForm'){const m=model.data.members.find(x=>x.id===d.memberId);if(!m)throw Error('Integrante no encontrado.');await addDoc(col('payments'),{memberId:m.id,memberName:m.name,amount:v('amount'),note:d.note.trim(),date:iso(),createdBy:model.user.uid,createdAt:serverTimestamp()});}
 if(f.id==='comparisonForm'){const r=ref('products',window.currentProduct);await runTransaction(model.db,async tx=>{const p=await tx.get(r);if(!p.exists())throw Error('Producto no encontrado');tx.update(r,{comparisons:[...(p.data().comparisons||[]),{source:d.source.trim(),price:v('price'),url:d.url.trim(),date:d.date,mode:'Manual'}]});});}
 if(f.id==='stockForm'){const r=ref('products',window.currentProduct),delta=Math.floor(v('delta'));if(!delta)throw Error('Escribe un ajuste distinto de cero.');await runTransaction(model.db,async tx=>{const p=await tx.get(r);if(!p.exists()||p.data().stock+delta<0)throw Error('El ajuste dejaría inventario negativo.');tx.update(r,{stock:increment(delta)});tx.set(ref('movements',uid()),{date:iso(),kind:'Ajuste manual',productId:window.currentProduct,qty:delta,note:d.note.trim(),by:model.user.uid,createdAt:serverTimestamp()});});}
 if(f.id!=='loginForm'&&f.id!=='registerForm'&&f.id!=='workspaceForm'&&f.id!=='joinForm'){document.querySelector('#modal')?.replaceChildren();render();}
 }catch(ex){err(ex);}finally{model.busy=false;}}
function csv(rows){return '\ufeff'+rows.map(r=>r.map(v=>{const value=String(v??'').replace(/^[=+@-]/,x=>"'"+x);return `"${value.replaceAll('"','""')}"`}).join(',')).join('\r\n');}
function csvData(kind){
 if(kind==='sales')return [['Fecha','Folio','Producto','Vendedor','Canal','Venta','Costo producto','Flete','Comisión plataforma','Otros costos','Utilidad antes vendedor','% vendedor','Comisión vendedor','Utilidad negocio'],...model.data.sales.filter(period).map(x=>[x.date,x.id,x.productName,x.sellerName,x.channel,x.price,x.cost,x.shipping,x.fee,x.other,profit(x),x.pct,commission(x),profit(x)-commission(x)])];
 if(kind==='products')return [['SKU','Producto','Categoría','Proveedor','Costo','Precio objetivo','Stock','Stock mínimo','Referencias'],...model.data.products.map(p=>[p.sku,p.name,p.category,p.supplier,p.cost,p.target,p.stock,p.minStock,(p.comparisons||[]).map(c=>`${c.source}: ${c.price} (${c.date}) ${c.url}`).join(' | ')])];
 if(kind==='purchases')return [['Fecha','Folio','Producto','Proveedor','Cantidad','Total','Estado','Llegada estimada'],...model.data.purchases.filter(period).map(p=>[p.date,p.id,p.productName,p.supplier,p.qty,p.total,p.status,p.eta])];
 if(kind==='ideas')return [['Fecha','Folio','Idea','Costo estimado','Venta objetivo','Estado','A favor','Investigar','En contra','Notas','URL'],...model.data.ideas.filter(period).map(x=>[x.date,x.id,x.name,x.cost,x.target,x.status,Object.values(x.votes||{}).filter(v=>v==='Comprar').length,Object.values(x.votes||{}).filter(v=>v==='Investigar').length,Object.values(x.votes||{}).filter(v=>v==='No comprar').length,x.notes,x.url])];
 if(kind==='team')return [['Integrante','Rol','Ventas','Ingreso generado','Utilidad generada','Comisión acumulada','Pagos registrados','Saldo'],...model.data.members.map(m=>{const mine=model.data.sales.filter(period).filter(x=>x.sellerId===m.id),due=mine.reduce((a,x)=>a+commission(x),0),paid=model.data.payments.filter(period).filter(x=>x.memberId===m.id).reduce((a,x)=>a+num(x.amount),0);return [m.name,m.role,mine.length,mine.reduce((a,x)=>a+num(x.price),0),mine.reduce((a,x)=>a+profit(x),0),due,paid,due-paid]})];
 return [['Fecha','Producto ID','Tipo','Cantidad','Motivo','Usuario'],...model.data.movements.filter(period).map(m=>[m.date,m.productId,m.kind,m.qty,m.note,m.by])];
}
function download(blob,name){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function exportCsv(kind){download(new Blob([csv(csvData(kind))],{type:'text/csv;charset=utf-8'}),`productos-china-${kind}-${model.month||'todo'}.csv`);}
function makePdf(kind){const docu=new jsPDF(),data=csvData(kind),labels={sales:'Ventas',products:'Productos',purchases:'Compras',ideas:'Ideas',team:'Balances',movements:'Movimientos'};let y=20;docu.setFontSize(17);docu.text(`Productos China - ${labels[kind]||kind}`,14,y);docu.setFontSize(10);docu.text(`Periodo: ${model.month||'Todos'}  |  Generado: ${iso()}  |  Registros: ${data.length-1}`,14,y+=9);docu.setFontSize(9);for(let i=1;i<data.length;i++){const row=data[i];const lines=docu.splitTextToSize(data[0].map((heading,n)=>`${heading}: ${row[n]??''}`).join('   |   '),180);if(y+lines.length*5+10>280){docu.addPage();y=18;}y+=8;docu.text(lines,14,y);y+=lines.length*5;docu.setDrawColor(225);docu.line(14,y,196,y);}if(data.length===1)docu.text('Sin registros para este periodo.',14,43);return docu.output('blob');}
function exportPdf(kind){download(makePdf(kind),`productos-china-${kind}-${model.month||'todo'}.pdf`);}
async function share(kind){const file=new File([makePdf(kind)],`productos-china-${kind}-${model.month||'todo'}.pdf`,{type:'application/pdf'});if(navigator.canShare?.({files:[file]})){try{await navigator.share({title:`Productos China - ${kind}`,files:[file]});}catch(e){if(e.name!=='AbortError')err(e);}}else{exportPdf(kind);alert('PDF descargado. Puedes adjuntarlo en tu correo o mensajería.');}}
function authScreen(message=''){view(`<div class="auth"><div class="auth-card"><div class="auth-logo">中</div><h1>Productos China</h1><p>Productos, compras, ventas y resultados en un mismo lugar.</p>${message?`<div class="notice">${esc(message)}</div>`:''}<form id="loginForm" class="fields">${field('Correo','email','email','','required')}${field('Contraseña','password','password','','required')}<button class="primary">Entrar</button></form><div class="actions">${button('Entrar con Google','google-login','secondary')}${button('Crear cuenta','register','secondary')}${button('Restablecer contraseña','reset-password','plain')}</div></div></div>`);}
function setupScreen(){const invite=new URLSearchParams(location.search).get('join');view(`<div class="auth"><div class="auth-card"><div class="auth-logo">中</div><h1>Hola, ${esc(model.user.email)}</h1><p>Configura tu equipo o acepta una invitación.</p>${invite?`<h3>Unirme a un equipo</h3><form id="joinForm" class="fields">${field('ID del equipo','workspaceId','text',invite,'required')}${field('Tu nombre','name','text','','required')}<button class="primary">Aceptar invitación</button></form>`:''}<h3>Crear mi propio equipo</h3><form id="workspaceForm" class="fields">${field('Nombre del equipo','name','text','Productos China','required')}${field('Tu nombre','memberName','text','','required')}<button class="secondary">Crear equipo</button></form>${button('Salir','logout','plain')}</div></div>`);}
async function attach(w){model.unsubs.forEach(u=>u());model.unsubs=[];model.workspace=w;const m=await getDoc(doc(model.db,'workspaces',w,'members',model.user.uid));if(!m.exists()){model.workspace=null;throw Error('No tienes acceso al equipo. Solicita una invitación.');}model.role=m.data().role;for(const name of Object.keys(model.data).filter(n=>n!=='invites'||model.role==='admin')){const unsubscribe=onSnapshot(col(name),snap=>{model.data[name]=snap.docs.map(d=>({id:d.id,...d.data()}));render();},error=>err(error));model.unsubs.push(unsubscribe);}render();}
async function signedIn(user){model.unsubs.forEach(u=>u());model.unsubs=[];model.user=user;model.workspace=null;if(!user){authScreen();return;}if(!user.emailVerified){view(`<div class="auth"><div class="auth-card"><h1>Verifica tu correo</h1><p>Enviamos un enlace a ${esc(user.email)}. Ábrelo y vuelve aquí.</p>${button('Ya verifiqué','reload-user','primary')} ${button('Reenviar correo','resend-verification','secondary')} ${button('Salir','logout','plain')}</div></div>`);return;}try{const profile=await getDoc(doc(model.db,'profiles',user.uid));if(profile.exists()&&profile.data().workspaceId)await attach(profile.data().workspaceId);else setupScreen();}catch(e){err(e);setupScreen();}}
app.addEventListener('click',e=>{const navButton=e.target.closest('[data-page]');if(navButton){model.page=navButton.dataset.page;render();return;}const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;if(a==='google-login')return signInWithPopup(model.auth,new GoogleAuthProvider()).catch(err);if(a==='register'){view(`<div class="auth"><div class="auth-card"><h1>Crear cuenta</h1><p>Confirma tu correo antes de unirte al equipo.</p><form id="registerForm" class="fields">${field('Correo','email','email','','required')}${field('Contraseña (mínimo 6 caracteres)','password','password','','required minlength="6"')}<button class="primary">Crear cuenta</button></form>${button('Ya tengo cuenta','back-login','plain')}</div></div>`);return;}if(a==='back-login')return authScreen();if(a==='reset-password'){const email=prompt('Correo para restablecer contraseña:');if(email)sendPasswordResetEmail(model.auth,email).then(()=>alert('Revisa tu correo.')).catch(err);return;}if(a==='reload-user')return model.user.reload().then(()=>signedIn(model.auth.currentUser)).catch(err);if(a==='resend-verification')return sendEmailVerification(model.user).then(()=>alert('Correo enviado.')).catch(err);try{action(a);}catch(ex){err(ex);}});
app.addEventListener('submit',submit);
view('<div class="auth"><div class="auth-card"><h1>Productos China</h1><p>Conectando…</p></div></div>');
try{const services=await connectFirebase();model.auth=services.auth;model.db=services.db;onAuthStateChanged(model.auth,signedIn,err);}catch(e){view(`<div class="auth"><div class="auth-card"><h1>Configuración pendiente</h1><div class="notice">${esc(e.message)}</div></div></div>`);}
